name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: yehaditii
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
